version: '3.8'

services:

  flask:
    build: .
    container_name: multipoints-route-flask
    restart: always
    environment:
      - APP_NAME=MultiPointsRouteAPI
    ports:
      - 127.0.0.1:9666:9666
